# Generated by Django 4.2.1 on 2023-08-14 07:06


from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_singular", models.CharField(max_length=128, unique=True)),
                ("name_plural", models.CharField(max_length=128, unique=True)),
                ("category", models.CharField(max_length=128)),
                (
                    "units",
                    models.CharField(max_length=64, null=True, blank=True),
                ),
                ("grams_per_unit", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientNutritionalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_per_gram", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="nutritional_information",
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="+",
                        to="ingredients.nutrient",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ingredientnutritionalinformation",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "nutrient"),
                name="ingredient_nutrient_unique_together",
            ),
        ),
    ]
