repos:
  # Mypy for static type checking
  - repo: local
    hooks:
    -   id: mypy
        name: mypy
        language: system
        entry: mypy
        types_or: [python, pyi]
        args: [ --config-file=mypy.ini ]
        exclude: (tests)|(migrations)|(settings)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

    # Basic pre-commit hooks provided by default
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
