# Generated by Django 5.1.6 on 2025-08-13 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipeembedding_model_savedrecipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeembedding",
            name="model",
            field=models.TextField(
                choices=[
                    ("text-embedding-3-small", "text-embedding-3-small"),
                    ("text-embedding-3-large", "text-embedding-3-large"),
                    ("fake", "fake"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="savedrecipe",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="user_can_only_save_recipe_once"
            ),
        ),
    ]
