# Generated by Django 5.1.6 on 2025-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipeembedding_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.TextField(
                default="https://ichef.bbc.co.uk/ace/standard/1600/food/recipes/how_to_make_fish_pie_56143_16x9.jpg.webp"
            ),
            preserve_default=False,
        ),
    ]
