# Generated by Django 5.0.4 on 2025-02-10 07:14

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

from nutrimise.domain import embeddings


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeAuthor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("methodology", models.TextField(blank=True)),
                (
                    "meal_times",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(
                            choices=[
                                ("BREAKFAST", "Breakfast"),
                                ("LUNCH", "Lunch"),
                                ("DINNER", "Dinner"),
                            ]
                        ),
                        size=None,
                    ),
                ),
                ("number_of_servings", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="recipes.recipeauthor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeEmbedding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vector", pgvector.django.vector.VectorField(dimensions=embeddings.EMBEDDING_DIMENSIONS)),
                ("prompt_hash", models.TextField()),
                (
                    "vendor",
                    models.TextField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("FAKE", "Fake"),
                            ("FAKE_NO_SERVICE", "Fake no service"),
                            ("BROKEN", "Broken"),
                        ]
                    ),
                ),
                (
                    "model",
                    models.TextField(
                        choices=[
                            ("text-embedding-3-small", "text-embedding-3-small"),
                            ("fake", "fake"),
                        ]
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_ingredients",
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                models.F("author"),
                models.F("name"),
                name="author_can_only_have_one_recipe_per_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeembedding",
            constraint=models.UniqueConstraint(
                fields=("recipe", "model"), name="unique_recipe_embedding_per_model"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                models.F("recipe"),
                models.F("ingredient"),
                name="ingredient_features_max_once_per_recipe",
            ),
        ),
    ]
