# Generated by Django 5.0.4 on 2025-02-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipeauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="recipes.recipeauthor",
                null=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="recipe",
            name="users_can_only_have_one_recipe_per_name",
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                models.F("author"),
                models.F("name"),
                name="author_can_only_have_one_recipe_per_name",
            ),
        ),
    ]
