// This file is auto-generated by @hey-api/openapi-ts

/**
 * RecipeList
 */
export type RecipeList = {
    /**
     * Recipes
     */
    recipes: Array<Recipe>;
};

/**
 * Version
 */
export type Version = {
    /**
     * Version
     */
    version: string;
};

/**
 * _Recipe
 */
export type Recipe = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Media Url
     */
    media_url: string;
};

export type GetHealthGeneralHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/general/health';
};

export type GetHealthGeneralHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVersionGeneralVersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/general/version';
};

export type GetVersionGeneralVersionGetResponses = {
    /**
     * Successful Response
     */
    200: Version;
};

export type GetVersionGeneralVersionGetResponse = GetVersionGeneralVersionGetResponses[keyof GetVersionGeneralVersionGetResponses];

export type ListRecipesRecipesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recipes/';
};

export type ListRecipesRecipesGetResponses = {
    /**
     * Successful Response
     */
    200: RecipeList;
};

export type ListRecipesRecipesGetResponse = ListRecipesRecipesGetResponses[keyof ListRecipesRecipesGetResponses];

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8001' | (string & {});
};