# Generated by Django 5.0.4 on 2025-02-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("pgvector", "0001_enable_vector_extension")]

    operations = [
        migrations.CreateModel(
            name="DietaryRequirement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngredientCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("units", models.CharField(max_length=64)),
                ("grams_per_unit", models.FloatField()),
                (
                    "dietary_requirements_satisfied",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ingredients",
                        to="ingredients.dietaryrequirement",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredients",
                        to="ingredients.ingredientcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientNutritionalInformation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity_per_gram", models.FloatField()),
                (
                    "units",
                    models.TextField(choices=[("GRAMS", "Grams"), ("KCAL", "kcal")]),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_information",
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ingredients.nutrient",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ingredientnutritionalinformation",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "nutrient"),
                name="ingredient_nutrient_unique_together",
            ),
        ),
    ]
