# Generated by Django 5.0.4 on 2025-02-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="units",
            field=models.CharField(max_length=64),
        ),
    ]
