# Generated by Django 4.2.1 on 2023-08-14 07:06

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_singular", models.CharField(max_length=128)),
                ("name_plural", models.CharField(max_length=128)),
                ("category", models.CharField(max_length=128)),
                (
                    "displayed_units_singular",
                    models.CharField(max_length=64, null=True, blank=True),
                ),
                (
                    "displayed_units_plural",
                    models.CharField(max_length=64, null=True, blank=True),
                ),
                ("grams_per_displayed_unit", models.FloatField()),
                ("protein_per_gram", models.FloatField()),
                ("carbohydrates_per_gram", models.FloatField()),
            ],
        ),
    ]
