# Generated by Django 5.1.6 on 2025-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuembedding",
            name="model",
            field=models.TextField(
                choices=[
                    ("text-embedding-3-small", "text-embedding-3-small"),
                    ("text-embedding-3-large", "text-embedding-3-large"),
                    ("fake", "fake"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="nutrientrequirement",
            name="units",
            field=models.TextField(
                choices=[
                    ("GRAMS", "g"),
                    ("MILLIGRAM", "mg"),
                    ("MICROGRAM", "μg"),
                    ("MICROGRAM_RETINOL_ACTIVITY_EQUIVALENT", "µg RAE"),
                    ("MICROGRAM_DIETARY_FOLATE_EQUIVALENT", "µg DFE"),
                    ("KCAL", "kcal"),
                ]
            ),
        ),
    ]
