name: Continuous integration

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install -r requirements/app-requirements.txt
        pip install -r requirements/test-requirements.txt
    - name: Run test suite with pytest
      run: pytest .

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    # We only want to have to install the dev requirements once
    - name: Install dev requirements
      run: |
        pip install -r requirements/app-requirements.txt
        pip install -r requirements/dev-requirements.txt
    - name: Run mypy on application code
      run: mypy ./reciply
    - name: Run black
      if: success() || failure()
      run: black .
    - name: Run isort on all python code
      if: success() || failure()
      run: isort . --profile=black
    - name: Run flake8 on all python code
      if: success() || failure()
      run: |
        flake8 ./reciply
        flake8 ./tests
