name: Continuous integration

on:
  push:
    branches: [ 'main' ]
  pull_request:
  workflow_dispatch:

env:
  # .env file is created by parsing a github secret at runtime
  ENV_FILE: .env

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          # Credentials required by postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_EXTENSIONS: vector
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: make install_ci_deps
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run test suite with pytest
        run: make test

      - name: Run mypy
        if: success() || failure()
        run: make mypy

      - name: Run ruff checker
        if: success() || failure()
        run: make check

      - name: Run import linter
        if: success() || failure()
        run: make lint_imports
