# Generated by Django 5.0.4 on 2025-02-03 06:49

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuEmbedding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vector", pgvector.django.vector.VectorField(dimensions=1024)),
                ("prompt_hash", models.TextField()),
                (
                    "vendor",
                    models.TextField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("FAKE", "Fake"),
                            ("FAKE_NO_SERVICE", "Fake no service"),
                            ("BROKEN", "Broken"),
                        ]
                    ),
                ),
                (
                    "model",
                    models.TextField(
                        choices=[
                            ("text-embedding-3-small", "text-embedding-3-small"),
                            ("fake", "fake"),
                        ]
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="menus.menu",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="menuembedding",
            constraint=models.UniqueConstraint(
                fields=("menu", "model"), name="unique_menu_embedding_per_model"
            ),
        ),
    ]
